### ISSUE TITLE
Tracking Issue: MVP of building controller UI

### ISSUE THREAD

**Issue by git-hulk** [apache/kvrocks-controller#135]
- [x] #136
- [x] #137
- [x] #138
- [x] #139
- [x] #140
- [x] #142
- [x] #141

**Comment by CulturalProfessor** [comment]
## Kvrocks Controller Web UI Task List

### Completed Tasks

- [x] https://github.com/apache/kvrocks-controller/issues/138
- [x] https://github.com/apache/kvrocks-controller/issues/139
- [x] https://github.com/apache/kvrocks-controller/issues/141 (Import Feature Remaining)

## In Progress

- [ ] **Import Feature for Clusters**
- [ ] **Namespaces Home page for status of all active namespaces**
- [ ] https://github.com/apache/kvrocks-controller/issues/140

**Comment by CulturalProfessor** [comment]
@jihuayu I've added some major features that are completed/ongoing , please review !

**Comment by shubham-j-sde** [comment]
Hey @git-hulk
I'd like to continue on these tasks, i am also [contributing](https://github.com/apache/kvrocks-website/pulls/shubham-j-sde) towards Kvrocks website, and have went through above links to understand changes and requirements.

**Comment by shubham-j-sde** [comment]
also, why's the package manager `npm`?  we are using Next.js framework, so the obvious choice is `pnpm`, as they [recommend](https://nextjs.org/learn/dashboard-app/getting-started#creating-a-new-project).
